### PR TITLE
Auto generate script for all in one configs

### PR DESCRIPTION
**Pull request by bghandchi**
A script to automatically make the necessary changes to the files in the `All in one fallbacks NGINX` folder.
Feature:

- Modifies all files automatically.
- Generates short links for all configs
- Generates one base64 string for all configs
- Generates separate qr codes for all configs

### CODE REVIEW

**Comment by yuhan6665** [comment]
Fancy. Thanks for your work!

**Comment by FranzKafkaYu** [comment]
@bghandchi Fantastic work, well done!

**Comment by bghandchi** [comment]
Thank you for merging :)

**Comment by wlfvpn** [comment]
@bghandchi why did you change the path for ?ed=2048 . This is to use 0RTT

**Comment by bghandchi** [comment]
@wlfvpn this is actually a mistake from my side. I was making some small changes in my fork. This change was after the pr. Didn't realize it ll automatically included in pr. We can change it back.

**Comment by bghandchi** [comment]
The real reason behind these small changes for me was that the short urls for configs were all okay for Android but there were problems for iOS. I was removing and changing parts of the configs urls to find out what the problem is.

**Comment by bghandchi** [comment]
Before you ask, you may be interested in knowing why I commented out the H2 and TCP configs. The reason is when the domains are behind a cdn eg Cloudflare, those configs won't connect. If the DNS is not proxied in Cloudflare they work perfectly.

**Comment by wlfvpn** [comment]
@bghandchi Thanks for clarification.  I would still recommend adding ?ed=2048 to the path to optimize 0RTT and also based on :
https://github.com/chika0801/Xray-examples/blob/main/warning.md
 

> Handshake: The WS in the inner layer of WSS needs to shake hands once more, and the timing characteristics are very unique. In fact, opening https://github.com/XTLS/Xray-core/pull/375 can alleviate the problem. If you have to use WSS, it is recommended?ed=2048

to avoid detection. I should mention the 0RTT should also be activated from the cloudflare CDN to get the benefit.

**Comment by Saoshyanet** [comment]
What you should also consider is that the URL format in the previous notes was wrong, I suggest that you pass them through v2rayNG and export them to get the correct URL format. For example the address should not contain "?" or "=" in the values of fields i.e "?path=/vlws?ed=2048" is wrong and "?path=%2Fvlws%3Fed%3D2048" is correct.

**Comment by Saoshyanet** [comment]
One ther note: You can also simplify the usage of sed for the users by using "#" notation in sed, that is, instead of 
`export main_domain_crt="\/path\/to\/main\/domain\/fullchain.pem"  # Change this to the correct value` we could have
`export main_domain_crt="/path/to/main/domain/fullchain.pem"  # Change this to the correct value` if we use the following sed notations: `sed -i "s#find#replace#g"`

**Comment by bghandchi** [comment]
Good points. I'll make some changes and make a new pr. As for the usage of sed I agree it can be done better. My plan was to it properly with jq and directly manipulate the jason. This way something like extra domain names can be supported easily. In the meantime anybody has any idea why the TCP and H2 configs won't work when the domain is proxied behind Cloudflare?

**Pull request merged**
